"""new fields in user model

Revision ID: 87cf08a6bce5
Revises: 38a161f5cb99
Create Date: 2023-03-13 11:42:34.012797

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87cf08a6bce5'
down_revision = '38a161f5cb99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
